version: '3'
services:
  php:
    tty: true
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./php:/var/www/php
      - php-vendor:/var/www/php/vendor
      - php-node-modules:/var/www/php/node_modules
  node:
    tty: true
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./client:/var/www/client
      - node-modules:/var/www/client/node_modules
volumes:
  php-vendor:
  php-node-modules:
  node-modules:
